# -*- coding: utf-8 -*-
"""ClassificationViaRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rr7gO7BP6vpKKlQ8MJ2XYfiO2s0-7NHt
"""

# Developed in Google Colaboratory
# Linear Regression Model

import tensorflow as tf
import pandas as pd
import numpy as np
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

# Create from CSV
# For use in colab with the file in the contents directory
Sup_train = pd.read_csv('./TrainingData.csv', header=None, names=["Low", "High", "Label"])
Sup_features = Sup_train.copy()
Sup_labels = Sup_features.pop('Label')
Sup_features = np.array(Sup_features)
Sup_features

# Generate model
Sup_model = tf.keras.Sequential([
  layers.Dense(64),
  layers.Dense(1)
])

Sup_model.compile(loss = tf.losses.MeanSquaredError(),
                      optimizer = tf.optimizers.Adam())

# Fit model
Sup_model.fit(Sup_features, Sup_labels, epochs=10)